# Generated by Django 4.0.1 on 2022-01-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('idDestino', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Destino')),
                ('nombreDestino', models.CharField(max_length=60, verbose_name='Nombre Destino')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.IntegerField(max_length=5, primary_key=True, serialize=False, verbose_name='Nro Reserva')),
                ('nombreCliente', models.CharField(max_length=60, verbose_name='Nombre Cliente')),
                ('precio', models.IntegerField(max_length=7, verbose_name='Precio')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destino')),
            ],
        ),
    ]
